### ISSUE TITLE
Re-import metadata

### ISSUE THREAD

**Issue by marshallbrain** [marshallbrain/image-gallery#13]
# Feature description
Re-import metadata from cashed data and replace existing data. Alternative mode in import images dialog.

# Tasks
- [ ] Replaces empty values by default
- [ ] Option per mapper that can replace existing data
- [ ] Remove image selection when enabled
