### ISSUE TITLE
Image view tabbing

### ISSUE THREAD

**Issue by marshallbrain** [marshallbrain/image-gallery#19]
# Description
Users should be able to tab through different fields in the image viewer
Order should be
- Image (selected on load)
- Tags (if metadata is open)
- Collections (if metadata is open)

# Tasks
- [ ] Image should be default
- [ ] Exclude speed dial from tab list
- [ ] Image > tag > collection > repeat
