### ISSUE TITLE
Collections

### ISSUE THREAD

**Issue by marshallbrain** [marshallbrain/image-gallery#2]
# Feature description
Creating a new collection and adding images to it

# Tasks
- [ ] Create new collection
- [ ] Add image to collection
- [ ] Remove image from collection
