### ISSUE TITLE
Add tag to all selected images

### ISSUE THREAD

**Issue by marshallbrain** [marshallbrain/image-gallery#33]
# Description
Should have an option to edit tags and collections when selecting multiple images. Should also show any tags that are shared between all images. Should be done by adding the image id to a temp table when selected.

# Tasks
- [ ] Show tag selector dialog
- [ ] Add and remove tags from all selected images
- [ ] Show common tags
