### ISSUE TITLE
Minor changes

### ISSUE THREAD

**Issue by marshallbrain** [marshallbrain/image-gallery#7]
# Feature description
Title

# Tasks
- [x] Clear images from "import images" dialog
- [x] Progress bar when importing images
- [ ] Clean up code
- [x] Refactor import images

**Comment by marshallbrain** [comment]
Refactored image importing and added a progress bar bbe5261a72c3b27c7c40c55a4a674e7ba13f4a4a
